### ISSUE TITLE
Week 1 Project Approval Ticket

### ISSUE THREAD

**Issue by iskapoor** [iskapoor/group-l#22]
- [x] Design - Wiki Theme, Brain Write & Wire Frame
- [Issue](https://github.com/iskapoor/group-l/issues/18)
- [x]  Technicals - 10 to 12 key idea
- [Issue](https://github.com/iskapoor/group-l/issues/19)
- [x]  Github - On Wiki containing Management Plan, forking, branching, pull request, etc
- [Issue](https://github.com/iskapoor/group-l/issues/21)
- [x]  Deployment - On Wiki containing Hardware, frequency, etc
- [Issue](https://github.com/iskapoor/group-l/issues/20)
- [x]  Scrum Board - Assignments and Backlog
- [Scrum Board](https://github.com/iskapoor/group-l/projects/1)

**Comment by rachelklee** [comment]
Github 1/1 - the policies are detailed and easy to follow
Design 1/1- Wireframe has been completed with extreme detail and brainstorming presents ideas for the future.
Deployment 0.75/1 - Missing info about how to update, update frequency, and update plan for when Deployment manager is absent. Deployment plan is also not fully completed (step 1,2,3 say "still working on this")
Scrum Board 0.75/1 - Missing backlog 1 week in advance. Tasks that are in backlog column are already completed (should be in review ready)
SCORE: 4.5/5

**Comment by jm1021** [comment]
Group L - Ishan 4.4/5
* No real work in this area .7/1
* Strong ideas and lots of details 1/1
* GitHub is detailed 1/1
* No real work in Deployment .7/1
* Issues seem like they have more details and thinking 1/1
