### ISSUE TITLE
W3 - Make design centered around rice

### ISSUE THREAD

**Issue by iskapoor** [iskapoor/group-l#40]
Create style of webpage to resemble a riced application.

**Comment by jlaaa** [comment]
Duplicate issue https://github.com/iskapoor/group-l/issues/13.

**Comment by algolg** [comment]
Many rices have navbars at the top and rounded corners on all windows. It is also popular to blur backgrounds in a way that may resemble frosted glass. We have implemented all of these.
Website:
![image](https://user-images.githubusercontent.com/55261146/146315820-1a4b526b-a19a-473b-b89c-c3152fe8fee0.png)
An example of what my riced desktop looks like
![image](https://user-images.githubusercontent.com/55261146/146316050-ddaa5725-30e1-4ca1-8a39-9bccf918f0a9.png)
