### ISSUE TITLE
About Pages

### ISSUE THREAD

**Issue by algolg** [iskapoor/group-l#42]
**Team** README quality, release day policies, Scrum Board to week after break

     -[ ]  1.0

     -[ ]  .75

     -[ ]  .5

     -[ ]  0
       Justification:

 Team: Deployed Web Site

     -[ ]  1.0

     -[ ]  .75

     -[ ]   .5

     -[ ]   0
       Justification:

 **Individual** About Pages on deployed on Site

     -[ ]   1.0

     -[ ]    .75

     -[ ]   .5

     -[ ]    0
       Justification:

 Page must use a Layout and have special customization (color pallet, background, etc)

     -[ ]   1.0

     -[ ]    .75

     -[ ]   .5

     -[ ]    0
       Justification:

 Picture with Mask that toggles to Picture of Choice (ie pic without mask). Perhaps ASCII art.

     -[ ]   1.0

     -[ ]    .75

     -[ ]   .5

     -[ ]    0
       Justification:

 Pull or show data (Web API) with information of interest

     -[ ]   1.0

     -[ ]    .75

     -[ ]   .5

     -[ ]    0
       Justification:

 Establish link(s) to journal and other key indicators of your work and progress on your home page (remember Tri 1 pop quiz)

     -[ ]   1.0

     -[ ]    .75

     -[ ]   .5

     -[ ]    0
       Justification:

 Store and Retrieve Data

     -[ ]   1.0

     -[ ]    .75

     -[ ]   .5

     -[ ]    0
       Justification:

 Unit #2 FRQ deployed

     -[ ]   1.0

     -[ ]    .75

     -[ ]   .5

     -[ ]    0
       Justification:

**Comment by iskapoor** [comment]
Individual About Pages on deployed on Site

-[ ]   1.0

 -[ ]    .75

 -[ ]   .5

 -[ ]    0
   Justification:
Page must use a Layout and have special customization (color pallet, background, etc)

 -[ ]   1.0

 -[ ]    .75

 -[ ]   .5

 -[ ]    0
   Justification:
Picture with Mask that toggles to Picture of Choice (ie pic without mask). Perhaps ASCII art.

 -[ ]   1.0

 -[ ]    .75

 -[ ]   .5

 -[ ]    0
   Justification:
Pull or show data (Web API) with information of interest

 -[ ]   1.0

 -[ ]    .75

 -[ ]   .5

 -[ ]    0
   Justification:
Establish link(s) to journal and other key indicators of your work and progress on your home page (remember Tri 1 pop quiz)

 -[ ]   1.0

 -[ ]    .75

 -[ ]   .5

 -[ ]    0
   Justification:
Store and Retrieve Data

 -[ ]   1.0

 -[ ]    .75

 -[ ]   .5

 -[ ]    0
   Justification:
Unit #2 FRQ deployed

 -[ ]   1.0

 -[ ]    .75

 -[ ]   .5

 -[ ]    0
   Justification:

**Comment by TKperson** [comment]
**Team** README quality, release day policies, Scrum Board to week after break

     -[ * ]  1.0

     -[ ]  .75

     -[ ]  .5

     -[ ]  0
       Justification: The quality is pretty good because the theme is uniform all the way through and everything in my about page is working correctly.


 Team: Deployed Web Site

     -[ * ]  1.0

     -[ ]  .75

     -[ ]   .5

     -[ ]   0
       Justification: I deployed the website correct and got a domain working


 **Individual** About Pages on deployed on Site

     -[ * ]   1.0

     -[ ]    .75

     -[ ]   .5

     -[ ]    0
       Justification: The about pages are all deployed on the site.


 Page must use a Layout and have special customization (color pallet, background, etc)

     -[ * ]   1.0

     -[ ]    .75

     -[ ]   .5

     -[ ]    0
       Justification: I had a monochrome theme (gray and white)


 Picture with Mask that toggles to Picture of Choice (ie pic without mask). Perhaps ASCII art.

     -[ * ]   1.0

     -[ ]    .75

     -[ ]   .5

     -[ ]    0
       Justification: It's is implemented and working properly on my about page


 Pull or show data (Web API) with information of interest

     -[ ]   1.0

     -[ ]    .75

     -[ ]   .5

     -[ ]    0
       Justification:


 Establish link(s) to journal and other key indicators of your work and progress on your home page (remember Tri 1 pop quiz)

     -[ ]   1.0

     -[ ]    .75

     -[ ]   .5

     -[ ]    0
       Justification:


 Store and Retrieve Data

     -[ ]   1.0

     -[ ]    .75

     -[ ]   .5

     -[ ]    0
       Justification:


 Unit #2 FRQ deployed

     -[ ]   1.0

     -[ ]    .75

     -[ ]   .5

     -[ ]    0
       Justification:

**Comment by jlaaa** [comment]
**Team** README quality, release day policies, Scrum Board to week after break

     -[x]  1.0

     -[ ]  .75

     -[ ]  .5

     -[ ]  0
       Justification: README, release policies, and Scrum Board all complete.


 Team: Deployed Web Site

     -[x]  1.0

     -[ ]  .75

     -[ ]   .5

     -[ ]   0
       Justification: Web site is deployed and can be accessed.


 **Individual** About Pages on deployed on Site

     -[x]   1.0

     -[ ]    .75

     -[ ]   .5

     -[ ]    0
       Justification: About page can be accessed on the deployed site.


 Page must use a Layout and have special customization (color pallet, background, etc)

     -[x]   1.0

     -[ ]    .75

     -[ ]   .5

     -[ ]    0
       Justification: About page as a unique layout and customization.


 Picture with Mask that toggles to Picture of Choice (ie pic without mask). Perhaps ASCII art.

     -[x]   1.0

     -[ ]    .75

     -[ ]   .5

     -[ ]    0
       Justification: Picture on about page that toggles on click.


 Pull or show data (Web API) with information of interest

     -[ ]   1.0

     -[ ]    .75

     -[ ]   .5

     -[x]    0
       Justification:


 Establish link(s) to journal and other key indicators of your work and progress on your home page (remember Tri 1 pop quiz)

     -[ ]   1.0

     -[ ]    .75

     -[ ]   .5

     -[x]    0
       Justification:


 Store and Retrieve Data

     -[ ]   1.0

     -[ ]    .75

     -[ ]   .5

     -[x]    0
       Justification:


 Unit #2 FRQ deployed

     -[x]   1.0

     -[ ]    .75

     -[ ]   .5

     -[ ]    0
       Justification: FRQ #2 deployed on about page.

**Comment by algolg** [comment]
Team: 2/2
1/1 for README and Scrum Tasks because our README includes all necessary information for anyone who comes across our page to commit and because our scrum board goes up to Week 4

1/1 for deployment because Michael worked on getting our website up on AWS and it is accessible through school filters. We also have a custom domain, though that does not work through school filters.

Individual: 6.5/7
0.75/1 because we have all of our about pages locally but they are not deployed (the deployed branch is older)

1/1 for design because our theme is original and we have a light and dark mode which transition smoothly

1/1 because my about page includes photos of me with and without a mask which toggle on click

0.75/1 because there is a local database but no RapidAPI database

1/1 because it includes a link to my journal at the top

1/1 because of the comments database to which users can send and retrieve comments

1/1 for FRQ deployment as part e of my frq can be accessed and tried
